analyzer:
  exclude:
    - build/**
    - bricks/**
    - lib/**/*.gr.dart
    - lib/**/*.iconfig.dart
    - lib/**/*.config.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - packages/**
    - test/fixtures/dia/**
  language:
    strict-casts: true
    strict-raw-types: true


  errors:
    directives_ordering: false
    # argument_type_not_assignable: false
    dead_code: warning
    duplicate_import: warning
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    unchecked_use_of_nullable_value: warning
    unused_element: warning
    unused_field: warning
    unused_import: warning
    unused_local_variable: warning
    always_declare_return_types: warning
    annotate_overrides: warning 
    avoid_catches_without_on_clauses: warning
    avoid_catching_errors: warning
    avoid_empty_else: warning
    avoid_function_literals_in_foreach_calls: warning
    avoid_init_to_null: warning
    avoid_returning_this: warning
    avoid_types_as_parameter_names: warning
    avoid_unnecessary_containers: warning
    camel_case_extensions: warning
    camel_case_types: warning
    cancel_subscriptions: warning
    close_sinks: warning
    curly_braces_in_flow_control_structures: warning
    empty_catches: warning
    empty_constructor_bodies: warning
    empty_statements: warning
    file_names: warning
    no_duplicate_case_values: warning
    null_closures: warning
    parameter_assignments: warning
    prefer_adjacent_string_concatenation: warning
    prefer_collection_literals: warning
    prefer_contains: warning
    prefer_final_fields: warning
    prefer_final_in_for_each: warning
    prefer_final_locals: warning
    prefer_if_null_operators: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_is_not_operator: warning
    prefer_null_aware_operators: warning
    prefer_spread_collections: warning
    prefer_typing_uninitialized_variables: warning
    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_declarations: warning
    recursive_getters: warning
    sized_box_for_whitespace: warning
    sort_child_properties_last: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_lambdas: warning
    unnecessary_new: warning
    unnecessary_null_aware_assignments: warning
    unnecessary_null_in_if_null_operators: warning
    unnecessary_overrides: warning
    unnecessary_parenthesis: warning
    unnecessary_statements: warning
    unnecessary_string_interpolations: warning
    unnecessary_string_escapes: warning
    use_key_in_widget_constructors: warning

linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_empty_else
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - cascade_invocations
    - control_flow_in_finally
    - close_sinks
    - curly_braces_in_flow_control_structures
    - do_not_use_environment
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - collection_methods_unrelated_type
    - file_names
    - hash_and_equals
    - implementation_imports
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_void_to_null
    - provide_deprecation_message
    - recursive_getters
    - sized_box_for_whitespace
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_pub_dependencies
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_string_interpolations
    - unnecessary_string_escapes
    - unnecessary_this
    - unrelated_type_equality_checks
    # - unawaited_futures
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_key_in_widget_constructors
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_to_and_as_if_applicable
    - valid_regexps
    - void_checks