name: dribble_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_route: ^7.8.2
  copy_with_extension: ^5.0.4
  copy_with_extension_gen: ^5.0.4
  cupertino_icons: ^1.0.2
  empty_widget: ^0.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.0
  json_annotation: ^4.8.1
  lorem_ipsum: ^0.0.3

dev_dependencies:
  analyzer: ^6.2.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.8 
  built_value_generator: ^8.9.1 
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 800
